apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - image: vprofile/vprofileapp:V1
        ports:
        - containerPort: 8080
          name: vproapp-port
      initContainers:
      - name: init-vprodb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb do echo waiting for mydb; sleep 2; done']
      - name: init-vpromc
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb do echo waiting for mydb; sleep 2; done']
      