apiVersion: v1
kind: Service
metadata:
  name: vpromc
spec:
  selector:
    labels:
    app: vpromc
  ports:
    - protocol: TCP
      port: 11211
      targetPort: vpromc-port
  selector:
    app: vpromc
  type: ClusterIP