apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
  labels:
    app: vprormq01
spec:
  selector:
    matchLabels:
      app: vprormq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vprormq01
    spec:
      containers:
        - name: vprormq01
          image: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER  # Correct the variable name
              value: guest

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:                  # Corrected indentation
                  name: app-secret
                  key: rmq-pass

          ports:
            - name: rabbitmq-port
              containerPort: 5672
       
